### ISSUE TITLE
problema su altervista

### ISSUE THREAD

**Issue by sacarde** [FlatNuke/flatnuke-2#1]
ciao,
   fino a qualche mese fa il mio sito ["sacarde.altervista.org"](http://sacarde.altervista.org) /" funizonava regolarmente
adesso se si tenta di accedere da il messaggio che si puo vedere,
la versione era una 257 alla 261(all'incirca...)
cosa puo essere successo? io non ho fatto alcuna modifica (forse un problema su php su altervista?)

cosa potrei fare?

grazie

**Comment by marcosegato** [comment]
Ciao, l'errore evidenzia che una funzione non è supportata dalla versione in utilizzo su Altervista: è possibile che di default abbiano impostato la 7.3, mentre per le vecchie versioni di Flatnuke servirebbe la 5.x
Nel pannello di Altervista puoi fare downgrade della versione PHP, verifica sul loro sito.
L'alternativa è migrare alla versione beta 4.0 di Flatnuke (https://github.com/FlatNuke/flatnuke): c'è lavoro da fare se parti dalla vecchissima 2.5.7, il progetto comunque non è più attivo/supportato.

**Comment by sacarde** [comment]
ok, ho downgradato php alla 5, e' riapparso il sito...

grazie
